name: lint

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup/action.yml

      - name: lint files
        run: pnpm lint
